In [1]:
import numpy as np
import pandas as pd

Question 1

What's the version of NumPy that you installed?

In [2]:
np.__version__

'1.22.3'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-13 00:22:58--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv.2’

data.csv.2          100%[===================>]   1.41M   509KB/s    in 2.8s    

2022-09-13 00:23:04 (509 KB/s) - ‘data.csv.2’ saved [1475504/1475504]



In [4]:
df = pd.read_csv("data.csv")

Question 2

How many records are in the dataset?

In [5]:
df.shape[0]

11914

Question 3

Who are the most popular car manufacturers (top-3) according to the dataset?

In [6]:
df['Make'].value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

Question 4

What's the number of unique Audi car models in the dataset?

In [7]:
df[df['Make'] == 'Audi']['Model'].nunique()

34

Question 5

How many columns in the dataset have missing values?

Ans = 5

In [8]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

Question 6

Find the median value of "Engine Cylinders" column in the dataset.

Next, calculate the most frequent value of the same "Engine Cylinders".

Use the fillna method to fill the missing values in "Engine Cylinders" with the most frequent value from the previous step.

Now, calculate the median value of "Engine Cylinders" once again.

Has it changed?

In [9]:
df['Engine Cylinders'].median()

6.0

In [10]:
df['Engine Cylinders'].mode()

0    4.0
Name: Engine Cylinders, dtype: float64

In [11]:
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(4.0)

In [12]:
df['Engine Cylinders'].median()

6.0

Ans - The median did not change

Question 7

Select all the "Lotus" cars from the dataset.

Select only columns "Engine HP", "Engine Cylinders".

Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows).

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Invert XTX.

Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the value of the first element of w?

In [13]:
lotus_cars = df[df['Make'] == 'Lotus']

In [14]:
hp_cylinder = lotus_cars[["Engine HP", "Engine Cylinders"]]
hp_cylinder

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [15]:
hp_cylinder = hp_cylinder.drop_duplicates()

In [16]:
hp_cylinder.shape[0]

9

In [17]:
X = hp_cylinder.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [18]:
XTX = np.dot(X.T, X)

In [19]:
X_inv = np.linalg.inv(XTX)
X_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [20]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [21]:
mat = np.dot(X_inv, X.T)

In [22]:
w = np.dot(mat, y)
w

array([  4.59494481, -63.56432501])

Ans = 4.59494481